# Reading Files
include:
  - .htaccess
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Site Settings
locale                   : "en-US"
title                    : "Henry H. Zhang"
description              : "PhD Candidate in Economics at MIT"
url                      : "https://henryhzhang.com"
baseurl                  : ""
repository               : "yourgithubusername/yourgithubusername.github.io"

# Site Author
author:
  name                   : "Henry H. Zhang"
  avatar                 : "images/photo.jpg"
  bio                    : "PhD Candidate in Economics at MIT"
  location               : "Cambridge, MA"
  employer               : "MIT"
  email                  : "hhz@mit.edu"
  uri                    : "https://economics.mit.edu/people/phd-students/henry-zhang"
  cv                     : "/files/CV.pdf"

# Analytics
analytics:
  provider               : false

# Footer
footer:
  links: []  # Removes social media links in footer