# Reading Files
include:
  - .htaccess
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Site Settings
title: "Henry H. Zhang"
description: "PhD Candidate in Economics at MIT"
url: "https://henryhzhang.com"  # change this to your domain
baseurl: ""  # leave this empty for GitHub Pages

# Site Author
author:
  name: "Henry H. Zhang"
  avatar: "assets/photo.jpg"  # make sure this path matches where you put your photo
  bio: "PhD Candidate in Economics at MIT"
  location: "Cambridge, MA"
  employer: "MIT"
  email: "hhz@mit.edu"
  uri: "https://economics.mit.edu/people/phd-students/henry-zhang"