theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Reading Files
include:
  - .htaccess
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Site Settings
locale                   : "en-US"
title                    : "Henry H. Zhang"
description              : "Assistant Professor of Finance"
url                      : "https://henryhzhang.com"
baseurl                  : ""
repository               : "heath-aster/heath-aster.github.io"

# Site Author
author:
  name                   : "Henry H. Zhang"
  avatar                 : "photo.jpg"
  bio                    : "Assistant Professor of Finance"
  location               : "Hong Kong"
  employer               : "CUHK Business School"
  email                  : "henryzhang@cuhk.edu.hk"
  uri                    : ""
  cv                     : "/files/CV.pdf"

# Analytics
analytics:
  provider               : false

# Footer
footer:
  links: []  # Removes social media links in footer